### ISSUE TITLE
[Feature Request] cron mode for `update` command

### ISSUE THREAD

**Issue by nuxencs** [browningluke/mangathr#109]
Currently the container exits after looking for new chapters once. It would be nice if you could configure a set interval at which the container continues to check for new chapters.

**Comment by browningluke** [comment]
Hey @nuxencs,

I thought about this when designing it, but decided that I wanted to keep the program as light as possible. To have it run continuously waiting for the interval would mean running a cron daemon within the container / program, which just adds more overhead.

Instead, just try running the container using the host system's cron daemon (whichever of the following works best for you):
```
0 0 * * * docker run ... browningluke/mangathr ... update ...
0 0 * * * mangathr update ...
``` 


Or, what I use is a K8s cronjob on my cluster. The helm files are here: https://github.com/browningluke-iac/helm-apps/blob/main/charts/mangathr/templates/cronjob-mangathr.yaml
